# Performance Configuration
performance:
  optimization:
    enabled: true
    level: "high"
    
  monitoring:
    metrics: true
    alerts: true
    dashboards: true
    
  security:
    scanning: true
    compliance: true
    hardening: true
    
  automation:
    ci_cd: true
    testing: true
    deployment: true
