name: Simple Fix
on:
  schedule:
    - cron: '0 2 * * 1'
  workflow_dispatch:

jobs:
  fix:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    
    steps:
    - uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Fix formatting
      run: |
        terraform fmt -recursive . 2>/dev/null || true
        find . -name "*.md" -exec sed -i 's/[[:space:]]*$//' {} \; 2>/dev/null || true
        
    - name: Commit changes
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "Auto Fix Bot"
        git add -A
        if ! git diff --staged --quiet; then
          git commit -m "auto-fix: formatting improvements"
          git push
        fi