name: Safe Auto Fix
on:
  schedule:
    - cron: '0 2 * * 1'
  workflow_dispatch:

jobs:
  auto-fix:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Safe fixes only
      run: |
        terraform fmt -recursive . 2>/dev/null || true
        find . -name "*.yml" -o -name "*.yaml" | xargs -I {} sed -i 's/[[:space:]]*$//' {} 2>/dev/null || true
        
    - name: Create PR for review
      uses: peter-evans/create-pull-request@v5
      with:
        title: 'Auto-fix: Safe formatting only'
        body: 'Only safe formatting changes - no dependency updates'
        branch: auto-fix/safe
        auto-merge-method: squash