name: Auto-merge Dependabot PRs

on:
  pull_request:
    types: [opened, synchronize, reopened]

permissions:
  contents: write
  pull-requests: write

jobs:
  auto-merge:
    if: github.actor == 'dependabot[bot]'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Check PR status
        id: pr-status
        run: |
          echo "Checking PR from dependabot..."
          echo "PR title: ${{ github.event.pull_request.title }}"
          
          # Only auto-merge security updates and patch versions
          if [[ "${{ github.event.pull_request.title }}" =~ (security|patch|chore) ]]; then
            echo "auto_merge=true" >> $GITHUB_OUTPUT
          else
            echo "auto_merge=false" >> $GITHUB_OUTPUT
          fi
      
      - name: Enable auto-merge
        if: steps.pr-status.outputs.auto_merge == 'true'
        run: |
          gh pr merge --auto --squash "${{ github.event.pull_request.number }}"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}