name: Security

on:
  schedule:
    - cron: '0 2 * * 1'
  workflow_dispatch:

jobs:
  security-scan:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Security Audit
      run: |
        echo "Running security audit..."
        
        # Check for sensitive patterns
        echo "Checking for sensitive data..."
        if find . -type f -name "*.md" -o -name "*.txt" -o -name "*.yml" | xargs grep -l "ghp_\|password.*[^REDACTED]\|secret.*[^REDACTED]\|token.*[^REDACTED]" 2>/dev/null; then
          echo "⚠️ Potential sensitive data found"
        else
          echo "✅ No sensitive data detected"
        fi
        
        # Check file permissions
        echo "Checking file permissions..."
        find . -type f -perm /o+w -not -path "./.git/*" | head -10
        
        echo "✅ Security scan completed"
